version: 2.1
jobs:
  check-dependant-repo: # defines a parameterized job
    description: A job that checks that updated libs don't break the builds based on this image.
    parameters:
      owner:
        description: "Github owner of the target repo"
        default: "bayesimpact"
        type: string
      repo:
        description: "Github name of the target repo"
        type: string
    machine: true
    steps:
      - checkout
      - run: .circleci/test_other_repo.sh "<< parameters.owner >>/<< parameters.repo >>"
  build:
    docker:
      - image: bayesimpact/circleci
    steps:
      - checkout
      - setup_remote_docker:
          # Allows to use previous cached version of the built Docker services.
          docker_layer_caching: true
      - run:
          name: Check that package.json is sorted.
          command: jq . package.json -S | diff - package.json
      - run:
          name: Check that the Dockerfile builds properly.
          command: docker build -t bayesimpact/react-base:$CIRCLE_BRANCH .
      - run:
          name: Publish docker image.
          command: |
            docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
            docker push "bayesimpact/react-base:$CIRCLE_BRANCH"
  publish:
    docker:
      - image: bayesimpact/circleci
    steps:
      - setup_remote_docker
      - run:
          name: Publish docker image.
          command: |
            docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
            docker tag "bayesimpact/react-base:$CIRCLE_BRANCH" "bayesimpact/react-base"
            docker push "bayesimpact/react-base"

workflows:
  version: 2.1
  build-test-publish:
    jobs:
      - build
      - check-dependant-repo:
          name: check-bob
          requires:
            - build
          repo: bob-emploi-internal
      - check-dependant-repo:
          name: check-cas-contact
          requires:
            - build
          repo: cas-contact-internal
      - publish:
          requires:
            - check-bob
            - check-cas-contact
          filters:
            branches:
              only:
                - master
                - /.*-test-deploy/

